Feature/update-filters
GFTOB/areadesenvolvedor-fase2 pull request #100
Opened 2021-02-25 19:06 UTC by eliseak

Atualização dos filtros conforme GT_Interfaces_Orientações_APIs_Fase_2_v1.3.0.pdf

2021-02-25 20:23 UTC, eliseak commented
Atualizado para versão v1.3.1

2021-02-26 12:59 UTC, luankevinferreira requested changes

2021-02-26 12:59 UTC, luankevinferreira commented on documentation/source/swagger/parts/_open_banking_apis_part.yml
> +    Page:
Verificar se a nomenclatura dos parâmetros do site ficam da maneira correta que é em minúsculo, por esse motivo que estavam definidos em minúsculo aqui.

2021-02-26 13:55 UTC, eliseak commented on documentation/source/swagger/parts/_open_banking_apis_part.yml
> +    Page:
Corrigido

2021-02-26 21:19 UTC, luankevinferreira commented
@eliseak ainda vai atuar nesse PR?

2021-02-26 21:25 UTC, eliseak commented
> @eliseak ainda vai atuar nesse PR?

Estava confusa com a nomenclatura dos endpoints. 
Acredito que é melhor corrigir eles primeiro (caso necessário) e fazer um rebase com a implementação dos filtros.

2021-02-26 21:25 UTC, closed without merging